<!-- resources/views/parts/print.blade.php -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parts Stock Acitivity Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px; /* Smaller font size */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 5px; /* Reduced padding for smaller size */
            text-align: left;
            font-size: 9px; /* Smaller text inside table cells */
            word-wrap: break-word; /* Allow long words to wrap */
            max-width: 120px; /* Limit width of the cells */
            text-overflow: ellipsis; /* Add ellipsis for overflowed content */
            white-space: nowrap; /* Prevent text from wrapping */
        }

        th {
            background-color: #f2f2f2;
            text-align: center;
        }

        td {
            text-align: left;
        }

        h2 {
            font-size: 14px; /* Smaller title */
        }
        .header-info {
            margin-bottom: 20px;
            font-size: 14px;
        }
        .footer-info {
            margin-top: 30px;
            font-size: 12px;
            text-align: right;
        }
        .action-in {
            background-color: #d4edda; /* Light green */
            color: #155724; /* Dark green text */
        }
        .action-out {
            background-color: #f8d7da; /* Light red */
            color: #721c24; /* Dark red text */
        }
    </style>
</head>
<body>
    <h1>Parts Stock Acitivity Report <br /> (From {{ $partsStockLog->first()->created_at }} to {{ $partsStockLog->last()->created_at }})</h1>
     <!-- Printed Date and User -->
     <div class="header-info">
        <p><strong>Printed on:</strong> {{ $currentDate }}</p>
        <p><strong>Printed by:</strong> {{ $currentUser }}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th >No</th>
                <th>Action</th>
                <th>Job Sequence</th>
                <th>Part Code</th>
                <th>Part Name</th>
                <th>Stock</th>
                <th>Action By</th>
                <th>Action Time</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach($partsStockLog as $key => $partLog)
            <tr>
                <td style="text-align: center;">{{$key+1}}</td>
                <td style="text-align: center;" class="{{ $partLog->action === 'IN' ? 'action-in' : ($partLog->action === 'OUT' ? 'action-out' : '') }}">
                    {{ $partLog->action }}
                </td>
                <td style="text-align: center;">{{ $partLog->ref_job_seq }}</td>
                <td>{{ $partLog->part_code }}</td>
                <td>{{ $partLog->part->name }}</td>
                <td style="text-align: center;">{{ $partLog->stock_change }} {{ $partLog->part->uom }}</td>
                <td style="text-align: center;">{{ $partLog->UserCreatedBy->full_name }} {{ $partLog->part->uom }}</td>
                <td style="text-align: center;">{{ $partLog->created_at }}</td>
                <td></td>
            </tr>
            @endforeach
        </tbody>
    </table>
        <!-- Footer: Optional Information -->
    <div class="footer-info">
        <p>Generated by System</p>
    </div>
</body>
</html>
