<!-- resources/views/parts/print.blade.php -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parts Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px; /* Decreased font size for the entire document */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 9px; /* Smaller font size for the table */
        }

        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 5px; /* Reduced padding */
            text-align: left;
        }
        th {
            text-align: center; /* Center the header text */
            background-color: #f2f2f2; /* Background color for header */
            font-weight: bold;
        }

        td {
            text-align: left;
        }

        .header-info {
            margin-bottom: 20px;
            font-size: 12px; /* Reduced font size for header info */
        }

        .footer-info {
            margin-top: 30px;
            font-size: 10px; /* Reduced font size for footer info */
            text-align: right;
        }

        /* For styling stock cells with different colors */
        .green {
            background-color: green;
            color: white;
        }

        .red {
            background-color: red;
            color: white;
        }

        .yellow {
            background-color: yellow;
            color: black;
        }
    </style>
</head>
<body>
    <h1>Parts Report</h1>
     <!-- Printed Date and User -->
     <div class="header-info">
        <p><strong>Printed on:</strong> {{ $currentDate }}</p>
        <p><strong>Printed by:</strong> {{ $currentUser }}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Code</th>
                <th>Name</th> 
                <th colspan="2">Stock</th>
                <th>UOM</th>
                <th>Actual Stock</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @foreach($parts as $index => $part)
            <tr>
                <td style="text-align: center;">{{ $index + 1 }}</td>
                <td>{{ $part->code }}</td>
                <td>{{ $part->name }}</td>
                <td style="text-align: center;">
                    @php
                    // Default to 0 if 'partStock' or 'stock' is null, and ensure 'min_stock' defaults to 0 if null
                    $stock = $part->partStock ? $part->partStock->stock : 0; 
                    $min_stock = $part->min_stock ?? 0; // Default to 0 if min_stock is null
                    $bgColor = 'green';  // Default color is green (ok)
                    $textColor = 'dark';  // Default text color is dark
                    
                    // Determine background color based on stock status
                    if ($stock <= 0) {
                        $bgColor = 'red'; // Out of stock
                    } elseif ($stock < $min_stock) {
                        $bgColor = 'yellow'; // Low stock
                    }
                @endphp
                
                {{ $stock }}
                <td style="background-color: {{ $bgColor }}; color: {{ $textColor }}; font-weight: bold;">
                    &nbsp;
                </td>
                </td>
                <td style="text-align: center;">{{ $part->uom }}</td>
                <td></td>
                <td></td>
            </tr>
            @endforeach
        </tbody>
    </table>
        <!-- Footer: Optional Information -->
    <div class="footer-info">
        <p>Generated by System</p>
    </div>
</body>
</html>
