<!-- resources/views/parts/print.blade.php -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parts Report</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        .header-info {
            margin-bottom: 20px;
            font-size: 14px;
        }
        .footer-info {
            margin-top: 30px;
            font-size: 12px;
            text-align: right;
        }
    </style>
</head>
<body>
    <h1>Parts Report</h1>
     <!-- Printed Date and User -->
     <div class="header-info">
        <p><strong>Printed on:</strong> {{ $currentDate }}</p>
        <p><strong>Printed by:</strong> {{ $currentUser }}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                {{-- <th>Description</th>
                <th>Category</th> --}}
                <th colspan="2">Stock</th>
                <th>UOM</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach($parts as $part)
            <tr>
                <td>{{ $part->code }}</td>
                <td>{{ $part->name }}</td>
                {{-- <td>{{ $part->description }}</td>
                <td>{{ $part->category_name }}</td> --}}
                <td>
                    @php
                        $stock = $part->partStock->stock ?? 0; // Default to 0 if stock is null
                        $min_stock = $part->min_stock ?? 0; // Default to 0 if min_stock is null
                        $bgColor = 'green';  // Default color is green (ok)
                        $textColor = 'dark';  // Default text color is dark
                        
                        // Determine background color based on stock status
                        if ($stock <= 0) {
                            $bgColor = 'red'; // Out of stock
                        } elseif ($stock < $min_stock) {
                            $bgColor = 'yellow'; // Low stock
                        }
                    @endphp

                    {{ $stock }}
                    <td style="background-color: {{ $bgColor }}; color: dark; font-weight: bold;">
                        &nbsp;
                    </td>
                </td>
                <td>{{ $part->uom }}</td>
                <td></td>
            </tr>
            @endforeach
        </tbody>
    </table>
        <!-- Footer: Optional Information -->
    <div class="footer-info">
        <p>Generated by System</p>
    </div>
</body>
</html>
