<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Slock PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px; /* Smaller font size */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 5px; /* Reduced padding for smaller size */
            text-align: left;
            font-size: 9px; /* Smaller text inside table cells */
        }

        th {
            background-color: #f2f2f2;
            text-align: center;
        }

        td {
            text-align: left;
        }

        h2 {
            font-size: 14px; /* Smaller title */
        }

        /* Optional: Add page breaks for better pagination in PDF */
        @media print {
            body {
                font-size: 9px; /* Smaller font size for print */
            }
            table {
                width: 100%;
                margin: 10px 0;
            }
        }
    </style>
</head>
<body>
    <h2>History Activity Stock Sloc Report (From {{ $stockSlockHistories->first()->date_income }} to {{ $stockSlockHistories->last()->date_income }})</h2>

    <table border="1" cellspacing="0" cellpadding="5">
        <thead>
            <tr>
                <th>No.</th>
                <th>Activity Time</th>
                <th>Slock Code</th>
                <th>Rack Code</th>
                <th>Job Seq</th>
                <th>Material</th> 
                <th>Valuated Stock</th>
                <th>Stock</th> 
                <th>Date Time</th>
                <th>Scanned By</th>
                <th>Status</th>
                <th>Date & Time Income</th>
                <th>Last Time Take In</th>
                <th>Last Time Take Out</th>
                <th>Take Location</th>
                <th>By User</th>
                <th>Tag</th>
                <th>Note</th> 
            </tr>
        </thead>
        <tbody>
            @foreach ($stockSlockHistories as $index => $item)
                <tr>
                    <td style="text-align: center; width:10px;">{{ $index + 1 }}</td> 
                    <td>{{ $item->created_at }}</td>
                    <td>{{ $item->slock_code }}</td>
                    <td>{{ $item->rack_code }}</td>
                    <td>{{ $item->job_seq }}</td>
                    <td>{{ $item->material ? $item->material->description : $item->material_code }}</td> 
                    <td>{{ $item->valuated_stock }} {{ $item->uom }}</td>
                    <td>{{ $item->stock }} {{ $item->uom }}</td> 
                    <td>{{ $item->date_time }}</td>
                    <td>{{ $item->scanned_by }}</td>
                    <td 
                        @if ($item->status === 'take_out') 
                            style="background-color: #f8d7da; color: #721c24;"  {{-- red-ish for take_out --}}
                        @elseif ($item->status === 'put_in') 
                            style="background-color: #d4edda; color: #155724;"  {{-- green-ish for put_in --}}
                        @else
                            style="background-color: #fefefe; color: #000;"     {{-- default fallback --}}
                        @endif
                    >
                        {{ $item->status }}
                    </td>
                    <td>{{ $item->date_income }} {{ $item->time_income }}</td>
                    <td>{{ $item->last_time_take_in }}</td>
                    <td>{{ $item->last_time_take_out }}</td>
                    <td>{{ $item->take_location }}</td>
                    <td>{{ $item->UserActionBy ? $item->UserActionBy->full_name : $item->user_id }}</td>
                    <td>{{ $item->tag }}</td>
                    <td>{{ $item->note }}</td> 
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div style="margin-top: 20px; text-align: center;">
        <p>Generated on {{ date('Y-m-d H:i:s') }}</p>
        <p>Generated by {{ auth()->user()->full_name }}</p>
    </div>
</body>
</html>